version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "11:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "@babel/core"
    versions:
    - 7.12.17
    - 7.13.10
    - 7.13.13
    - 7.13.8
  - dependency-name: polka
    versions:
    - 1.0.0-next.13
  - dependency-name: "@types/node"
    versions:
    - 14.14.28
    - 14.14.32
    - 14.14.33
    - 14.14.34
    - 14.14.35
    - 14.14.36
    - 14.14.39
    - 14.14.41
    - 15.0.0
  - dependency-name: esbuild
    versions:
    - 0.10.0
    - 0.10.1
    - 0.11.0
    - 0.11.10
    - 0.11.12
    - 0.11.13
    - 0.11.15
    - 0.11.9
    - 0.8.39
    - 0.8.40
    - 0.8.46
    - 0.8.47
    - 0.8.51
    - 0.8.54
    - 0.8.55
    - 0.8.57
    - 0.9.0
    - 0.9.2
    - 0.9.3
    - 0.9.4
    - 0.9.6
    - 0.9.7
  - dependency-name: postcss
    versions:
    - 8.2.12
    - 8.2.7
    - 8.2.8
  - dependency-name: rollup
    versions:
    - 2.38.1
    - 2.39.0
    - 2.39.1
    - 2.40.0
    - 2.41.0
    - 2.41.1
    - 2.41.2
    - 2.41.3
    - 2.41.4
    - 2.41.5
    - 2.43.1
    - 2.44.0
  - dependency-name: "@babel/preset-env"
    versions:
    - 7.12.17
    - 7.13.0
    - 7.13.10
    - 7.13.8
    - 7.13.9
  - dependency-name: "@babel/runtime"
    versions:
    - 7.13.4
    - 7.13.8
    - 7.13.9
  - dependency-name: "@babel/plugin-transform-runtime"
    versions:
    - 7.13.4
    - 7.13.7
    - 7.13.8
    - 7.13.9
  - dependency-name: svelte
    versions:
    - 3.32.3
  - dependency-name: "@rollup/plugin-node-resolve"
    versions:
    - 11.1.1
