version: '3'
services:
  keycloak:
    image: quay.io/keycloak/keycloak-x:12.0.3
    ports:
      - 8080:8080
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KEYCLOAK_LOGLEVEL=DEBUG
    restart: always
    volumes:
      - ./realm-export.json:/opt/keycloak/sirixdb-realm.json
      - ./create-sirix-users.sh:/opt/jboss/startup-scripts/create-sirix-users.sh
    command:
      - "start-dev -Dkeycloak.migration.action=import
        -Dkeycloak.migration.provider=singleFile -Dkeycloak.migration.file=/opt/keycloak/sirixdb-realm.json
        -Dkeycloak.migration.strategy=OVERWRITE_EXISTING"
  server:
    image: sirixdb/sirix
    ports:
      - 9443:9443
    restart: always
    volumes:
      - /opt/sirix/sirix-data:/opt/sirix/sirix-data
      - ./sirix-docker-conf.json:/opt/sirix/sirix-docker-conf.json
